translate Injections.md to ja
ray-di/ray-di.github.io pull request #26
Opened 2022-02-26 09:06 UTC by 77web

2022-02-26 09:13 UTC, 77web commented
@koriym review please :pray:

2022-02-26 09:30 UTC, koriym requested changes

2022-02-26 09:30 UTC, koriym commented on manuals/1.0/ja/Injections.md
> -は、依存関係を渡すことを推奨しています。依存関係を設定するプロセス
ちなみに、この機械翻訳の誤訳はコピーした時に文中に入った改行がそのままになってることで起こります！

2022-02-26 09:30 UTC, koriym commented on manuals/1.0/ja/Injections.md
> +オブジェクトに依存を注入するプロセスを *インジェクション* と呼びます。
```suggestion
オブジェクトに依存をセットするプロセスを *インジェクション* と呼びます。
```

2022-02-26 09:30 UTC, koriym commented on manuals/1.0/ja/Injections.md
> +オブジェクトに依存を注入するプロセスを *インジェクション* と呼びます。
機会翻訳は

"オブジェクトに依存性を設定する処理を*インジェクション*と呼びます。"です

2022-02-26 09:30 UTC, koriym commented on manuals/1.0/ja/Injections.md
> +## コンストラクタ・インジェクション
```suggestion
## コンストラクターインジェクション
```
こっちの方がより多く使われてるようです。

2022-02-26 09:30 UTC, koriym commented on manuals/1.0/ja/Injections.md
> +## セッター・インジェクション
```suggestion
## セッターインジェクション
```

2022-02-26 09:30 UTC, koriym commented on manuals/1.0/ja/Injections.md
> +## プロパティ・インジェクション
```suggestion
## プロパティインジェクション
```

2022-02-26 09:30 UTC, koriym commented on manuals/1.0/ja/Injections.md
> +Ray.Diはプロパティ・インジェクションをサポートしていません。
```suggestion
Ray.Diはプロパティインジェクションをサポートしていません。
```

2022-02-26 09:30 UTC, koriym commented on manuals/1.0/ja/Injections.md
> +## アシスト・インジェクション
```suggestion
## アシストインジェクション
```

2022-02-26 09:30 UTC, koriym commented on manuals/1.0/ja/Injections.md
> +メソッドコール・インジェクション、アクション・インジェクション、インボケーション・インジェクションとも呼ばれます。この場合、引数の最後に依存関係を追加し、パラメータに `#[Assisted]` を追加してください。そのパラメータには、デフォルトで `null` が必要です。
```suggestion
メソッドコールインジェクション、アクションインジェクション、インボケーションインジェクションとも呼ばれます。この場合、引数リストの最後に依存関係を追加し、パラメータに `#[Assisted]` を追加してください。そのパラメータには、デフォルトで `null` が必要です。
```

2022-02-26 09:30 UTC, koriym commented on manuals/1.0/ja/Injections.md
> +Ray.Diは、依存が利用できない場合、それらを黙って無視するようになります。そのため
```suggestion
Ray.Diは、依存が利用できない場合、それらを黙って無視するようになります。そのための
```

2022-02-26 09:30 UTC, koriym commented on manuals/1.0/ja/Injections.md
> +オプションインジェクションを使用するには、 `#[Inject(optional: true)`attribute を適用します。
```suggestion
オプションインジェクションを使用するには、 `#[Inject(optional: true)`属性を加えます。```

2022-02-26 09:30 UTC, koriym commented
@77web @NaokiTsuchiya さんのスーパーレビューも受けましょう！

2022-02-26 11:42 UTC, NaokiTsuchiya commented on manuals/1.0/ja/Injections.md
> +また、メソッド呼び出しの際に、他の動的パラメータに依存する依存関係を指定することができます。`MethodInvocationProvider` は [MethodInvocation](https://github.com/ray-di/Ray.Aop/blob/2.x/src/MethodInvocation.php) オブジェクトを提供します。
`指定することができます` は冗長な表現なので `指定できます` とするのはどうでしょうか。

```suggestion
また、メソッド呼び出しの際に、他の動的パラメータに依存する依存関係を指定できます。`MethodInvocationProvider` は [MethodInvocation](https://github.com/ray-di/Ray.Aop/blob/2.x/src/MethodInvocation.php) オブジェクトを提供します。
```

2022-02-26 11:42 UTC, NaokiTsuchiya commented on manuals/1.0/ja/Injections.md
> +Ray.Diは、依存が利用できない場合、それらを黙って無視するようになります。そのため
ここは文章の切れ目が変わっているので、自動翻訳が上手くいっていない箇所でしょうか。

en側の文章の変更も必要ですが、 `Method and field injections may be optional` は `Setter injections may be optional` とするのが良さそうですかね。field はサポートしていないですし、method injection は setter injection として扱っているので



```suggestion
依存関係が存在する場合はそれを使用し、存在しない場合はデフォルトにフォールバックするのが便利な場合があります。セッターインジェクションはオプションで、依存関係が利用できない場合、Ray.Diはそれらを黙って無視するようになります。
```

2022-02-26 12:58 UTC, koriym commented
https://github.com/ray-di/ray-di.github.io/issues/4#issue-1145284514
注意を追記しました！

2022-02-27 04:34 UTC, NaokiTsuchiya approved these changes

2022-02-27 04:51 UTC, koriym approved these changes

2022-02-28 05:59 UTC, merged