Translate AOP and add some sections in English
ray-di/ray-di.github.io pull request #29
Opened 2022-02-27 00:36 UTC by koriym

* 元のAOPを改めてGuice Wikiからインポートしました。少し英文も増えてます。 (complimentがcomplementにスペルミスが修正されてました！）
* NullInterceptorの部分はオリジナルです

2022-02-28 04:09 UTC, NaokiTsuchiya commented on manuals/1.0/ja/AOP.md
> +...そして、それを傍受する必要のあるメソッドに適用します。
l.89 では `intercepted` -> `インターセプト` となっているので、　`傍受` -> `インターセプト` でも良いかなと感じました。 

```suggestion
...そして、それをインターセプトする必要のあるメソッドに適用します。
```

2022-02-28 06:07 UTC, koriym commented on manuals/1.0/en/AOP.md
> +*   Methods must be public or protected
外しましょう！

2022-02-28 08:30 UTC, koriym commented on manuals/1.0/en/AOP.md
> +*   Methods must be public or protected
```suggestion
*   Methods must be public
```

2022-02-28 13:16 UTC, NaokiTsuchiya requested changes

2022-02-28 13:16 UTC, NaokiTsuchiya commented on manuals/1.0/ja/AOP.md
> +* メソッドは`public`または`protected`でなければならない
```suggestion
* メソッドは`public`でなければならない
```

2022-02-28 13:44 UTC, NaokiTsuchiya approved these changes

2022-02-28 14:00 UTC, koriym commented
@suzumaze ping

2022-03-01 10:09 UTC, suzumaze approved these changes

2022-03-01 10:11 UTC, merged