Change for Ray.Di: ModulesShouldBeFastAndSideEffectFree
ray-di/ray-di.github.io pull request #38
Opened 2022-02-27 16:28 UTC by koriym

2022-02-28 14:00 UTC, NaokiTsuchiya requested changes

2022-02-28 14:00 UTC, NaokiTsuchiya commented on manuals/1.0/en/bp/ModulesShouldBeFastAndSideEffectFree.md
> +        $webserver = $injector->getInstance(WebserverService.class, Service.class);
```suggestion
        $webserver = $injector->getInstance(WebserverService::class, Service::class);
```

2022-02-28 14:11 UTC, NaokiTsuchiya reviewed
第2引数に指定しているのは、 本文内で定義されている `ServiceInterface` ?

2022-02-28 14:11 UTC, NaokiTsuchiya commented on manuals/1.0/en/bp/ModulesShouldBeFastAndSideEffectFree.md
> +        $databaseConnectionPool = $injector->getInstance(DatabaseService::class, Service::class);
```suggestion
        $databaseConnectionPool = $injector->getInstance(DatabaseService::class, ServiceInterface::class);
```

2022-02-28 14:11 UTC, NaokiTsuchiya commented on manuals/1.0/en/bp/ModulesShouldBeFastAndSideEffectFree.md
> +        $webserver = $injector->getInstance(WebserverService::class, Service::class);
```suggestion
        $webserver = $injector->getInstance(WebserverService::class, ServiceInterface::class);
```

2022-02-28 15:58 UTC, koriym commented on manuals/1.0/en/bp/ModulesShouldBeFastAndSideEffectFree.md
> +        $databaseConnectionPool = $injector->getInstance(DatabaseService::class, Service::class);
getInstance()の２番目の引数はQualifierだからInterfaceはおかしいですね。

2022-02-28 16:04 UTC, koriym commented on manuals/1.0/en/bp/ModulesShouldBeFastAndSideEffectFree.md
> +        $databaseConnectionPool = $injector->getInstance(DatabaseService::class, Service::class);
これは逆ですね。ServiceInterface::classで、Qualifierが`DatabaseService`

2022-02-28 16:09 UTC, koriym commented
```java
Key.get(Service.class, WebserverService.class))
```

これがインタフェーフェイス＋識別子ですね。MentalModelであったように。

2022-03-01 02:10 UTC, NaokiTsuchiya commented on manuals/1.0/en/bp/ModulesShouldBeFastAndSideEffectFree.md
> +        $databaseConnectionPool = $injector->getInstance(DatabaseService::class, Service::class);
もとの実装ちゃんとみれてませんでした。これで良さそうですね

2022-03-01 02:13 UTC, NaokiTsuchiya commented on manuals/1.0/en/bp/ModulesShouldBeFastAndSideEffectFree.md
> +        $webserver = $injector->getInstance(WebserverService::class, Service::class);
`$databaseConnectionPool`になってますね

```suggestion
        $webserver = $injector->getInstance(ServiceInterface::class, WebserverService::class);
```

2022-03-01 11:37 UTC, merged