Translate InstanceBindings.md to ja
ray-di/ray-di.github.io pull request #43
Opened 2022-02-28 01:51 UTC by momospnr

refs #4

2022-02-28 01:55 UTC, momospnr commented on manuals/1.0/ja/InstanceBindings.md
> +注意：アプリケーションの起動パフォーマンスへの影響があるため、単純な値オブジェクトのような、それ自体に依存性を持たないオブジェクトにのみ使用してください。
[BEAR.Sundayのドキュメント日本語版、インスタンス束縛](https://bearsunday.github.io/manuals/1.0/ja/di.html#:~:text=getQualifiers()%3B%20//%20(array)%20%24qualifierAnnotations%5B%5D-,%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%B3%E3%82%B9%E6%9D%9F%E7%B8%9B,-toInstance()%E3%81%A7%E5%80%A4)を参考にしました。

サンプルコードの順番を入れ替えたりしてしまっているので
元の思想から外れているようでしたら直しますのでご指摘ください:bow:

2022-02-28 08:51 UTC, koriym requested changes
元の英語のがよくなかったですね。すいません！

2022-02-28 08:51 UTC, koriym commented on manuals/1.0/ja/InstanceBindings.md
> +値を直接束縛できます。定数の束縛に使います。
```suggestion
ある型をその型のインスタンスにバインドすることができます。これは通常、値オブジェクトのような、それ自体に依存性がないオブジェクトにのみ使用します。
```

2022-02-28 08:51 UTC, koriym commented on manuals/1.0/ja/InstanceBindings.md
> +オブジェクトの束縛にも使用できますが、注意が必要です。
```suggestion
作成が複雑なオブジェクトではインスタンス束縛を使用しないようにしてください。インスタンスはシリアライズ保存されるので、シリアライズ不可能なものはインスタンス束縛を使う事ができません。代わりにプロバイダ束縛を使用することができます。
```

Ray.Diはシリアライズできないと言う点を追加しました。

2022-02-28 08:51 UTC, koriym commented on manuals/1.0/ja/InstanceBindings.md
> +注意：アプリケーションの起動パフォーマンスへの影響があるため、単純な値オブジェクトのような、それ自体に依存性を持たないオブジェクトにのみ使用してください。
```suggestion
```

2022-02-28 08:51 UTC, koriym commented on manuals/1.0/ja/InstanceBindings.md
> +注意：アプリケーションの起動パフォーマンスへの影響があるため、単純な値オブジェクトのような、それ自体に依存性を持たないオブジェクトにのみ使用してください。
BEAR.Sundayのマニュアルは簡単に説明しすぎてましたね。専用ドキュメントサイトなのでGuice Wikiから改めてインポートしたのと、内部実装の事情も付加しました。

2022-02-28 09:45 UTC, momospnr commented on manuals/1.0/ja/InstanceBindings.md
> +注意：アプリケーションの起動パフォーマンスへの影響があるため、単純な値オブジェクトのような、それ自体に依存性を持たないオブジェクトにのみ使用してください。
ほとんどやり直していただいてしまって、お手数おかけしました！

2022-02-28 09:45 UTC, momospnr commented on manuals/1.0/ja/InstanceBindings.md
> +値を直接束縛できます。定数の束縛に使います。
ありがとうございます！
提案いただいた文に直しました。

2022-02-28 09:47 UTC, momospnr commented on manuals/1.0/ja/InstanceBindings.md
> +オブジェクトの束縛にも使用できますが、注意が必要です。
`インスタンスはシリアライズ保存されるので、シリアライズ不可能なものはインスタンス束縛を使う事ができません。`

この仕様、なんとなく使っていたので全然知りませんでした。。
勉強になります…！

2022-02-28 09:47 UTC, momospnr commented on manuals/1.0/ja/InstanceBindings.md
> +注意：アプリケーションの起動パフォーマンスへの影響があるため、単純な値オブジェクトのような、それ自体に依存性を持たないオブジェクトにのみ使用してください。
こちらはごそっと削除しました。

2022-02-28 09:48 UTC, koriym approved these changes

2022-02-28 09:52 UTC, koriym commented on manuals/1.0/ja/InstanceBindings.md
> +オブジェクトの束縛にも使用できますが、注意が必要です。
シリアライズ以外でオブジェクトのインスタンスをリクエストを超えて保存する方法がないですね！

GuiceWikiでは遅くなるっていってるんですけど、Ray.Diでは逆にシリアライズして保存（キャッシュ）するので速くなリマス。(!) しかしその中で保存されてしまうと他とシングルトンで共有とかでできなくなってしまいます。

2022-02-28 09:54 UTC, koriym commented on manuals/1.0/ja/InstanceBindings.md
> +注意：アプリケーションの起動パフォーマンスへの影響があるため、単純な値オブジェクトのような、それ自体に依存性を持たないオブジェクトにのみ使用してください。
いえいえ、これは元のが問題でした！

2022-02-28 13:39 UTC, NaokiTsuchiya commented on manuals/1.0/ja/InstanceBindings.md
> +ある型をその型のインスタンスにバインドすることができます。これは通常、値オブジェクトのような、それ自体に依存性がないオブジェクトにのみ使用します。
上記よりは、`束縛します。` の方が良さそうですかね。

```suggestion
ある型をその型のインスタンスに束縛します。これは通常、値オブジェクトのような、それ自体に依存性がないオブジェクトにのみ使用します。
```

2022-02-28 13:56 UTC, NaokiTsuchiya approved these changes

2022-03-01 10:09 UTC, suzumaze approved these changes

2022-03-01 10:10 UTC, merged