Translate ProviderBindings.md to Japanese
ray-di/ray-di.github.io pull request #44
Opened 2022-02-28 08:28 UTC by jingu

2022-02-28 09:21 UTC, koriym requested changes
オリジナルの日本語の[インジェクションポイント](https://github.com/ray-di/Ray.Di/blob/2.13.3/README.ja.md#インジェクションポイント)の説明が良くないと思い書き直しました。（お手数かけまてすいません！🙇‍♂️）

2022-02-28 09:21 UTC, koriym commented on manuals/1.0/ja/ProviderBindings.md
> +プロバイダ実装classはそれ自身でも依存性を持っており、コンストラクタを介して依存性を受け取ることができます。
```suggestion
プロバイダはそれ自身でも依存性を持っており、コンストラクタを介して依存性を受け取ります。  
```

元は`プロバイダ実装class` ですが`プロバイダ`の方が簡単で良いと思いました。でどうでしょうか？

2022-02-28 09:21 UTC, koriym commented on manuals/1.0/ja/ProviderBindings.md
> +`InjectionPointInterface` は次のメソッドを提供します。
```suggestion
`InjectionPointInterface` は以下のメソッドを提供します。
```

2022-02-28 09:21 UTC, koriym commented on manuals/1.0/ja/ProviderBindings.md
> +**InjectionPoint** はインジェクションポイントに関する情報をもつクラスです。
```suggestion
`InjectionPoint`オブジェクトは、注入が行われる箇所（インジェクションポイント）のメタ情報を持つクラスです。プロバイダは、注入箇所のクラス名や変数名などのインジェクションポイントのメタデータを使って依存インスタンスを作成する事ができます。
```

2022-02-28 09:21 UTC, koriym commented on manuals/1.0/ja/ProviderBindings.md
> +メタデータへのアクセスは、 `RefrectionParameter` または `Provider` 属性によって行われます。
```suggestion
```

2022-02-28 09:21 UTC, koriym commented on manuals/1.0/ja/ProviderBindings.md
> +例えば、 `Psr3LoggerProvier` クラスの `get()` メソッドは、インジェクト可能なLoggerを作成します。
```suggestion
### 例：インスタンス生成にインジェクションポイントのクラス名を使用

インジェクションポイントのクラス名を`$this->ip->getClass()->getName()`で取得して依存インスタンスを生成しています。
```

2022-02-28 09:21 UTC, koriym commented on manuals/1.0/ja/ProviderBindings.md
> +Loggerのログカテゴリは、それがインジェクトされる対象のオブジェクトのクラスに依存しています。
```suggestion
```

2022-03-01 01:12 UTC, jingu commented on manuals/1.0/ja/ProviderBindings.md
> +プロバイダ実装classはそれ自身でも依存性を持っており、コンストラクタを介して依存性を受け取ることができます。
同感です！

2022-03-01 01:34 UTC, koriym approved these changes

2022-03-01 07:14 UTC, koriym commented
@NaokiTsuchiya @suzumaze お願いします！

2022-03-01 07:18 UTC, suzumaze approved these changes

2022-03-01 15:31 UTC, NaokiTsuchiya approved these changes

2022-03-01 23:40 UTC, merged