Add Best Practices
ray-di/ray-di.github.io pull request #46
Opened 2022-03-01 12:19 UTC by koriym

* Best Practicesをメニュー追加 (en, ja)
* jaフォルダに英語のBest Practicesをコピー

2022-03-01 15:40 UTC, NaokiTsuchiya commented on manuals/1.0/en/BestPractices.md
>  *   [Don't reuse binding annotations (aka `#[Qualifiers]`)](bp/dont_reuse_annotations.html)
https://github.com/ray-di/ray-di.github.io/blob/master/manuals/1.0/en/bp/DontReuseAnnotations.md#dont-reuse-binding-attributes-aka-attribute に合わせました。

```suggestion
*   [Don't reuse binding annotations (aka `#[Attribute]`)](bp/dont_reuse_annotations.html)
```

2022-03-01 15:40 UTC, NaokiTsuchiya commented on manuals/1.0/ja/BestPractices.md
> +*   [バインディングアトリビュートを再利用しない (`#[Qualifiers]`)](bp/dont_reuse_annotations.html)
```suggestion
*   [バインディングアトリビュートを再利用しない (`#[Attribute]`)](bp/dont_reuse_annotations.html)
```

2022-03-01 15:40 UTC, NaokiTsuchiya commented on manuals/1.0/ja/bp/DontReuseAnnotations.md
> +permalink: /manuals/1.0/ja/bp/dont_reuse_annotations.html
en版もですが、 `Don't reuse binding attributes (aka `#[Attribute]`)` としているので、 `annotations` -> `attributes` とするのはどうでしょうか。ファイル名も要変更ですが。

```suggestion
permalink: /manuals/1.0/ja/bp/dont_reuse_attributes.html
```

2022-03-01 23:36 UTC, koriym commented on manuals/1.0/en/BestPractices.md
>  *   [Don't reuse binding annotations (aka `#[Qualifiers]`)](bp/dont_reuse_annotations.html)
元が間違えてますね！　"binding annotations" がQualifiersですね。

2022-03-01 23:37 UTC, koriym commented on manuals/1.0/ja/BestPractices.md
> +*   [バインディングアトリビュートを再利用しない (`#[Qualifiers]`)](bp/dont_reuse_annotations.html)
これも同じく元が間違えてる

2022-03-02 16:10 UTC, koriym commented on manuals/1.0/ja/bp/DontReuseAnnotations.md
> +permalink: /manuals/1.0/ja/bp/dont_reuse_annotations.html
ここはスキップしましょう！名残ということURL doesn't matterというRWABookからの...😅

2022-03-03 16:30 UTC, NaokiTsuchiya requested changes

2022-03-03 16:30 UTC, NaokiTsuchiya commented on manuals/1.0/en/BestPractices.md
>  *   [Don't reuse binding annotations (aka `#[Qualifiers]`)](bp/dont_reuse_annotations.html)
```suggestion
*   [Don't reuse binding attributes (aka `#[Qualifiers]`)](bp/dont_reuse_annotations.html)
```

2022-03-08 11:12 UTC, merged

2022-03-08 11:12 UTC, koriym commented
7日経過したので一旦mergeします。