Add Tutorial (JA)
ray-di/ray-di.github.io pull request #66
Opened 2022-06-06 03:28 UTC by koriym

2022-06-06 05:17 UTC, NaokiTsuchiya requested changes

2022-06-06 05:17 UTC, NaokiTsuchiya commented on manuals/1.0/ja/Tutorial1.md
> +DIのコードは基本的にこのように依存をコンストラクタで渡してオブジェクトが相互依存するオブジェクトグラフを生成します。オブジェクトはル他から所有されているか、他を所有しているか、あるいは双方のいずれかです。
```suggestion
DIのコードは基本的にこのように依存をコンストラクタで渡してオブジェクトが相互依存するオブジェクトグラフを生成します。オブジェクトは他から所有されているか、他を所有しているか、あるいは双方のいずれかです。
```

2022-06-06 05:17 UTC, NaokiTsuchiya commented on manuals/1.0/ja/Tutorial1.md
> +次に今`Printer`で固定している挨拶のメッセージも多国語に対応するようため注入するように変更します。
```suggestion
次に今`Printer`で固定している挨拶のメッセージも多国語対応するために注入するように変更します。
```

2022-06-06 05:38 UTC, koriym commented
内容どうでしょうか？
モチベーションとかと重複しすぎてるでしょうか？
それとも重複してるからこそハンズオンとしてはありでしょうか？

2022-06-07 02:49 UTC, h13 commented
アンターゲット束縛は、 manuals のほうでもよいかもなとも思いましたが、実際手を動かしてみるとこういう使い方もできるのかと視野は拡がりそうですね。
私はすごくよいチュートリアルだと思いました。

2022-06-07 03:24 UTC, koriym commented
> アンターゲット束縛は、 manuals のほうでもよい

これはどういうことでしょうか？

2022-06-07 06:08 UTC, koriym commented
@h13 あ、ここでは説明しないでマニュアルにあるから良いってことでしょうか？

2022-06-08 06:22 UTC, koriym commented
Gentle reminder @NaokiTsuchiya @suzumaze

2022-06-08 07:22 UTC, h13 commented
そうですね。マニュアルにあるのでって意図でした。
チュートリアルがちょい複雑化するのでどうかなと思った次第です。 @koriym

2022-06-08 09:33 UTC, NaokiTsuchiya approved these changes

2022-06-08 15:29 UTC, koriym commented
@NaokiTsuchiya 迷った時は要素の少ない方にしてみます！一旦 アンターゲット束縛をrevertしてmergeします。

2022-06-08 15:29 UTC, merged

2022-06-08 15:30 UTC, koriym commented
https://ray-di.github.io/manuals/1.0/ja/tutorial1.html