Translate Motivation
ray-di/ray-di.github.io pull request #9
Opened 2022-02-22 10:50 UTC by koriym

Related #4

2022-02-23 04:13 UTC, NaokiTsuchiya requested changes

2022-02-23 04:13 UTC, NaokiTsuchiya commented on manuals/1.0/ja/Motivation.md
> +ファクトリーは必要ありませんし、テストケースを単純化するために`setUp` と `tearDown` が使えます。
> We don’t need any factories, and we can simplify the testcase by removing the setUp and tearDown boilerplate:

原文は上記で、ここでは前述のテストの実装と比較して、`setUp と tearDown での factory 操作（定型的なコード）が不要になった` ことについて触れていおいた方が良いと感じました。以下のような感じでどうでしょうか。 

```suggestion
ファクトリーは必要ありませんし、`setUp` と `tearDown` の定型的なコードを削除することで、テストケースを簡素化することができます。
```

2022-02-23 04:15 UTC, NaokiTsuchiya commented on manuals/1.0/ja/Motivation.md
> +しかし、最大の問題は依存関係がコードの中に **隠されていること** です。もし私たちが `CreditCardFraudTracker` への依存関係を追加したら、どのテストが壊れるか見つけるためにテストを再実行しなければなりません。もし、プロダクションサービスのファクトリーを初期化するのを忘れた場合、課金が行われるまでそのことに気がつきません。アプリケーションが大きくなるにつれて、ファクトリ
改めて読んでますが、ここすごく良いこと書いてありますね！

2022-02-23 04:19 UTC, koriym commented on manuals/1.0/ja/Motivation.md
> +ファクトリーは必要ありませんし、テストケースを単純化するために`setUp` と `tearDown` が使えます。
良いですね！

2022-02-23 04:24 UTC, NaokiTsuchiya approved these changes

2022-02-23 10:47 UTC, koriym commented on manuals/1.0/ja/Motivation.md
> +しかし、最大の問題は依存関係がコードの中に **隠されていること** です。もし私たちが `CreditCardFraudTracker` への依存関係を追加したら、どのテストが壊れるか見つけるためにテストを再実行しなければなりません。もし、プロダクションサービスのファクトリーを初期化するのを忘れた場合、課金が行われるまでそのことに気がつきません。アプリケーションが大きくなるにつれて、ファクトリ
DIの事を十分に知っててもこのGuiceユーザーガイドは改めて読む価値がありますね！

2022-02-25 05:29 UTC, koriym commented on manuals/1.0/ja/Motivation.md
> +## Ray.Diによる依存性注入
```suggestion
## Ray.Diによる依存性の注入
```

2022-02-25 05:31 UTC, suzumaze requested changes

2022-02-25 05:31 UTC, suzumaze commented on manuals/1.0/ja/Motivation.md
> +このコードは、モジュール性とテスト容易性の点で問題があリます。実際のクレジットカード・プロセッサーに直接依存すると、このコードをテストするとクレジットカードに課金されてしまいます！また、チャージが拒否されたときやサービスが利用できないときに何が起こるかをテストするのは厄介です。
```suggestion
このコードは、モジュール性とテスト容易性の点で問題があります。実際のクレジットカード・プロセッサーに直接依存すると、このコードをテストするとクレジットカードに課金されてしまいます！また、チャージが拒否されたときやサービスが利用できないときに何が起こるかをテストするのは厄介です。
```

2022-02-25 05:31 UTC, suzumaze commented on manuals/1.0/ja/Motivation.md
> +品質の問題は、QAや受入テストによって発見されることは発見されるでしょう。しかし、もっといい方法があるはずです。
```suggestion
品質の問題は、QAや受け入れテストによって発見されることは発見されるでしょう。しかし、もっといい方法があるはずです。
```

2022-02-25 05:31 UTC, suzumaze commented on manuals/1.0/ja/Motivation.md
> +## Ray.Diによる依存性注入
```suggestion
## Ray.Diによる依存性の注入
```

2022-02-25 05:31 UTC, suzumaze commented on manuals/1.0/ja/Motivation.md
> +依存性注入パターンは、モジュール化されたテスト可能なコードを導き、Ray.Diで簡単にコードを書けるようにします。課金の例でRay.Diを使うには、まずインターフェイスとその実装をどのように対応付けるかを指示する必要があります。設定は`Module` インターフェースを実装したRay.Diモジュールクラスで行われます。
```suggestion
依存性の注入パターンは、モジュール化されたテスト可能なコードを導き、Ray.Diで簡単にコードを書けるようにします。課金の例でRay.Diを使うには、まずインターフェイスとその実装をどのように対応付けるかを指示する必要があります。設定は`Module`インターフェースを実装したRay.Diモジュールクラスで行われます。
```

2022-02-25 05:39 UTC, koriym commented on manuals/1.0/ja/Motivation.md
> +ファクトリーと同様、依存性注入も単なるデザインパターンに過ぎません。核となる原則は、依存関係の解決から振る舞いを **分離する** ことです。この例では、 `RealBillingService` は `TransactionLog` と `CreditCardProcessor` を探す責任はありません。代わりに、コンストラクタのパラメータとして渡されます。
```suggestion
ファクトリーと同様、依存性の注入も単なるデザインパターンに過ぎません。核となる原則は、依存関係の解決から振る舞いを **分離する** ことです。この例では、 `RealBillingService` は `TransactionLog` と `CreditCardProcessor` を探す責任はありません。代わりに、コンストラクタのパラメータとして渡されます。
```

2022-02-25 05:40 UTC, koriym commented on manuals/1.0/ja/Motivation.md
> +## Ray.Diによる依存性注入
```suggestion
## Ray.Diによる依存性の注入
```

2022-02-25 05:48 UTC, merged